/*
 * This is the main class which contain main() function. This will check for master password and go to buckets class if master password is correct.
 * 
 * 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * master_password.java
 *
 * Created on Nov 29, 2011, 7:09:12 PM
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JOptionPane;

import com.amazonaws.services.s3.AmazonS3;

/**
 *
 * @author Koteshwar
 */
public class master_password extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public master_password() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        master_password_label = new javax.swing.JLabel();
        master_password_enter_button = new javax.swing.JButton();
        master_password_cancel_button = new javax.swing.JButton();
        master_password_text = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        master_password_label.setText("Master Password :");

        master_password_enter_button.setText("Enter");
        master_password_enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_password_enter_buttonActionPerformed(evt);
            }
        });

        master_password_cancel_button.setText("Cancel");
        master_password_cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_password_cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(master_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(master_password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(master_password_enter_button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(master_password_cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(master_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(master_password_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(master_password_enter_button)
                    .addComponent(master_password_cancel_button))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

@SuppressWarnings("deprecation")
private void master_password_enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                             
	
	
	//Master Password Entered by User
	masterpassword=master_password_text.getText();
            
	//Master Password from the file
	
	File file = new File("masterpassword.txt"); 
	  FileReader fr;
	try {
		fr = new FileReader(file);
		BufferedReader br = new BufferedReader(fr);
	
	//Comparing Master Password from file with user entered password
	if(masterpassword.contentEquals(br.readLine())){
		this.setVisible(false);
		new buckets(s3,masterpassword).setVisible(true);
		fr.close();
		}
    else if(master_password_text.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Password field cannot be Empty","Error",JOptionPane.ERROR_MESSAGE);	
         }
    else{
        JOptionPane.showMessageDialog(null, "Incorrect Master Password","Error",JOptionPane.ERROR_MESSAGE);
        master_password_text.setText("");
        }
	} 
	  catch (FileNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}                                                            

private void master_password_cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                              
	System.exit(0);
}                                                             

    /**
     * @param args the command line arguments
     * @throws IOException 
     */
    public static void main(String args[]) throws IOException {
    	
    	Authentication auth = new Authentication();
    	s3 =auth.Authentiication();
    		//s3 = new AmazonS3Client(new PropertiesCredentials(master_password.class.getResourceAsStream("AwsCredentials.properties")));
    	//S3Object masterfile = s3.getObject(new GetObjectRequest(master_password_bucket, masterpassword_name));

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master_password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton master_password_cancel_button;
    private javax.swing.JButton master_password_enter_button;
    private javax.swing.JLabel master_password_label;
    private javax.swing.JPasswordField master_password_text;
    private String masterpassword ;
    String master_password_bucket;
    String master_password_name;
    static AmazonS3 s3,dup;
    String masterpass;
    // End of variables declaration
}
